include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/intl/*.dart
    - lib/**/*.g.dart
    - lib/utils/multi-languages/*.dart

linter:
  rules:
    overridden_fields: false
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false
    depend_on_referenced_packages: false

